---
- name: 'Creating VirtualHost Configuration File'
  hosts: amazon
  become: yes
  vars:
    domain: www.example.com
    mysql_root_password: mysqlroot123
    mysql_user: wpuser
    mysql_password: wpuser123
    mysql_database: wordpress 
        
  tasks:
    - name: 'Installing Apache'
      yum: name=httpd,php,php-mysql state=present
        
    - name: 'Creating Virtualhost Configuration File'
      template:
        src: virtualhost.j2
        dest: /etc/httpd/conf.d/{{domain}}.conf
    
    - name: 'Creating Document Root'
      file:
        path: /var/www/html/{{domain}}
        state: directory
        owner: apache
        group: apache
        mode: 0755
            
    - name: 'Creating index.html'
      copy:
        content: '<h1><center>It Works</center></h1>'
        dest: /var/www/html/{{domain}}/index.html
            
    - name: 'Restarting Apache Webserver'
      service:
        name: httpd
        state: restarted
        enabled: true
 - name: 'Mariad-server Installing'
      yum: name=MySQL-python,mariadb-server state=present
        
    - name: 'Mariadb-server Restarting/Enabling '
      service: name=mariadb state=restarted enabled=yes
     
    - name: 'Mariadb-server Resetting Root Password'
      ignore_errors: true
      mysql_user:
        login_user: root
        login_password: ''
        name: root
        password: "{{mysql_root_password}}"
        host_all: true
            
    - name: 'Mariadb-server Removing Anonymous users'
      mysql_user:
        login_user: root
        login_password: "{{mysql_root_password}}"
        name: ''
        state: absent
        host_all: true
            
            
    - name: 'Mariadb-server Creating Additional database'
      mysql_db:
        login_user: root
        login_password: "{{mysql_root_password}}"
        name: "{{mysql_database}}"
        state: present
            
    - name: 'Mariadb-server Creating additional user/password'
      mysql_user:
        login_user: root
        login_password: "{{mysql_root_password}}"
        name: "{{mysql_user}}"
        password: "{{mysql_password}}"
        state: present
        host: localhost
        priv: "{{mysql_database}}.*:ALL"
    - name: 'wordpress - Downloading'
      get_url:
        url: https://wordpress.org/wordpress-4.5.8.tar.gz
        dest: /tmp/wordpress.tar.gz
            
    - name: 'Wordpress - Extraction'
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /tmp/
        remote_src: yes
            
    - name: 'Wordpress - Copying Wordpress To DocumentRoot'
      shell: 'cp -r /tmp/wordpress/*  /var/www/html/{{domain}}'
        
    - name: 'Wordpress - Creating wp-config.php'
      template:
        src: wp-config.php.j2
        dest: /var/www/html/{{domain}}/wp-config.php
